blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/hTPdYK2Qg5
    about: Ask questions and discuss with other IPForce community members 
  - name: Website
    url: https://openscilab.com/
    about: Check out our website for more information
